name: dbatools blog
title: dbatools blog | A blog theme for PowerShell dbatools
description: This is a dedicated blog site to the awesome PowerShell module named DBATOOLS if you work with SQL you need this module. Read more here.
tags:
  - blog
  - template
  - jekyll
  - theme
  - dbatools
  - powershell
email: adambacon1@hotmail.com
show_hero: true
